# generate kube join command for joining the node to the Kubernetes cluster and store the command in the file named join-command.
- name: Generate join command
  command: kubeadm token create --print-join-command
  register: join_command

- name: Copy join command to local file
  local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="/tmp/join-command.sh" mode=0777

- name: Storing join command to s3 bucket {{ s3_bucket }}
  aws_s3:
    bucket: "{{ s3_bucket }}"
    object: /join-commnad.sh
    src: ./join-command
    mode: put
