---
- hosts: kubernetes-master-nodes
  become: yes
  roles:
    - role: master/common-packages
    - role: master/disabling-swaping
    - role: master/install-kubelet
    - role: master/init-kubernetes-cluster
    - role: master/setup-user-to-access-cluster
    - role: master/container-networking
    - role: master/join-nodes-to-cluster
  # setup a handler for checking Docker daemon using the below code.
  handlers:
    - name: docker status
      service: name=docker state=started