# generate kube join command for joining the node to the Kubernetes cluster and store the command in the file named join-command.

# - name: Getting join-command.sh from bucket {{ s3_bucket }}
#   aws_s3:
#     bucket: "{{ s3_bucket }}"
#     object: join-command.sh
#     dest: /tmp/join-command.sh
#     mode: get

- name: Copy the join command to server location
  copy: 
    src: ../join-command.sh
    dest: /tmp/join-command.sh

- name: Join the node to cluster
  become: yes
  become_user: root
  command: eval $(cat /tmp/join-command.sh)
